config/routes.rb
Rails.application.routes.draw do

  
  resources :designers
  root 'pages#home'

  resources :sals do 
    collection do
      get 'archive'
    end
    resources :releases
  end

  resources :tags

  resources :features do
    collection do
      get 'completed'
    end
    member do
      put "like", to: "features#upvote"
      put "dislike", to: "features#downvote"
    end
  end

  get '/about', to: 'pages#about', as: 'about'
  devise_for :users 
  resources :user_flosses
  resources :flosses do
    member do
      put "increase", to: "flosses#increase"
      put "decrease", to: "flosses#decrease"
    end
  end
  resources :fabrics
  get '/projects', to: 'projects#all', as: 'projects'
  get '/projects/dashboard', to: 'projects#dashboard', as: 'dashboard'
  get '/projects/dashboard/archive', to: 'projects#archive', as: 'archive'
  get '/projects/dashboard/wishlist', to: 'projects#wishlist', as: 'wishlist'
  get '/projects/dashboard/all', to: 'projects#dashboardall', as: 'dashboardall'
  resources :users, only: [:index, :show, :all] do
    resources :projects do
      member do
        put "like", to: "projects#like"
        put "dislike", to: "projects#dislike"
      end
      resources :updates
    end
  end

  get "/flosses/increase_with_jquery/:id", to: "flosses#increase_with_jquery"
  get "/flosses/decrease_with_jquery/:id", to: "flosses#decrease_with_jquery"
end

app/models/sal.rb
class Sal < ApplicationRecord
  validates :name, :company, :tag, presence: true
  validates :name, uniqueness: true
  belongs_to :tag
  has_many :releases
  mount_uploader :picture, PictureUploader

  def released_on
    date = self.start_date
    date.strftime("#{date.day.ordinalize}")
  end

  def company_link
    self.link.split('/').first
  end

end

app/controllers/sals_controller.rb
class SalsController < ApplicationController
  def index
    @sals = Sal.where("end_date >= ?", Time.current)
  end

  def archive
    @sals = Sal.where("end_date <= ?", Time.current)
  end

  def show
    @sal = Sal.find(params[:id])
    @projects = @sal.tag.projects
    @releases = @sal.releases.order(created_at: :desc)
    @releases = @releases.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @sal = Sal.new
  end

  def create
    @sal = Sal.new(sal_params)
    respond_to do |format|
      if @sal.save
        format.html { redirect_to sals_path, notice: 'Sal was successfully created.' }
        format.json { render :show, status: :created, location: @sal }
      else
        format.html { render :new }
        format.json { render json: @sal.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @sal = Sal.find(params[:id])
  end

  def update
    @sal = Sal.find(params[:id])
    respond_to do |format|
      if @sal.update(sal_params)
        format.html { redirect_to sals_path, notice: 'Sal was successfully updated.' }
        format.json { render :show, status: :ok, location: @sal }
      else
        format.html { render :edit }
        format.json { render json: @sal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @sal = Sal.find(params[:id])
    @sal.destroy
    respond_to do |format|
      format.html { redirect_to sals_path, notice: 'Sal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def sal_params
      params.require(:sal).permit(:name, :company, :picture, :start_date, :end_date, :notes, :link, :tag_id)
    end

end

app/helpers/sals_helper.rb
module SalsHelper
end

app/views/sals/_projects.html.erb
<% if @projects.exists? %>
<div class="row bootstrap snippets" id="real-estates-columns">
<h2 class="text-center">Members stitching <%= @sal.name %></h2></br>
  <% @projects.each do |project| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
          <% if project.picture? %>
            <%= link_to image_tag(project.picture, class: "img-responsive"), user_project_path(project.user, project) %>
          <% else %>
            <%= link_to image_tag("noimage.jpeg", class: "img-responsive"), user_project_path(project.user, project) %>
          <% end %>
            <div class="title-realestates-columns">
              <h4><%= link_to project.name, user_project_path(project.user, project) %><%= link_to project.status, "#", class: "btn btn-primary pull-right" %></h4>
              <% if project.start_date %>
                  <%= project.start_date.strftime("%b %d, %Y") %> -
                  <% else %>
                    Not Started
                  <% end %>
                  <% if project.finish_date %>
                    <%= project.finish_date.strftime("%b %d, %Y") %> 
                  <% end %>
              <hr>
            </div>
            <% if project.user == current_user && project.private == true %>
              <%= link_to "Private", user_project_path(project.user, project), class: "btn btn-danger" %>
              <%= link_to  '#', class: "btn btn-danger pull-right" do %>
                  <i class="fa fa-heart" aria-hidden="true">
                      <%= project.get_likes.size %>
                  </i>
              <% end %>
            <% elsif project.user == current_user %>
              <%= link_to "View", user_project_path(project.user, project), class: "btn btn-primary" %>
              <%= link_to  '#', class: "btn btn-danger pull-right" do %>
                  <i class="fa fa-heart" aria-hidden="true">
                    <%= project.get_likes.size %>
                  </i>
              <% end %>
            <% else %>
                <%= link_to project.user.username, user_projects_path(project.user), class: "btn btn-primary" %>
              <% if current_user %>
                <% if current_user.liked? project %>
                  <%= link_to  dislike_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                    <i class="fa fa-heart" aria-hidden="true">
                      <% if project.get_likes.size > 0 %>
                        <%= project.get_likes.size %>
                      <% else %>
                      Like
                      <% end %>
                    </i>
                  <% end %>
                <% else %>
                  <%= link_to  like_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                    <i class="fa fa-heart-o" aria-hidden="true">
                      <% if project.get_likes.size > 0 %>
                        <%= project.get_likes.size %>
                      <% else %>
                      Like
                      <% end %>
                    </i>
                  <% end %>
                <% end %>
               <% end %> 
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<% end %>

app/views/sals/_releases.html.erb
<div class="row bootstrap snippets" id="real-estates-columns">
<% if @sal.releases %>
  <% @releases.each do |release| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
          <h2 class="text-center"><%= release.name %></h2></br>
          <%= image_tag(release.picture, class: "img-responsive") %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>
<div class="text-center">
  <%= will_paginate @releases, renderer: BootstrapPagination::Rails %>
</div>

app/views/sals/_sal.html.erb
  <div class="col-md-4 col-sm-6 col-xs-12">
    <div class="panel">
      <div class="panel-body">
        <h2 class= "text-center"><%= link_to sal.name, sal_path(sal) %></h2>
        <hr>
          <% if sal.picture? %>
              <%= image_tag(sal.picture, class: "thumbnail") %>
          <% else %>
              <%= image_tag("noimage.jpeg", class: "thumbnail") %>
          <% end %>
          <div class="title-realestates-columns">
            <h3 class="text-center"><%= sal.company %></h3>
            <hr>
            <% if sal.start_date %>
              <h4 class="text-center"><%= sal.start_date.strftime("%b %d, %Y") %>
            <% else %>
              <h4 class="text-center">Not Started
            <% end %>
            <% if sal.end_date && sal.start_date %>
              - <%= sal.end_date.strftime("%b %d, %Y") %></h4>
            <% elsif sal.start_date %>
              - Not Finished</h4>
            <% end %>
          </div> 
      </div>
    </div>
  </div>  


app/views/sals/archive.html.erb
<%= link_to "Current SALs", sals_path, class: "btn btn-success padding btn-lg" %>
<div class="row bootstrap snippets" id="real-estates-columns">
  <%= render @sals %>
</div>

app/views/sals/edit.html.erb
<h1>Edit <%= @sal.name %></h1>

<%= simple_form_for(@sal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :company %>
    <%= f.input :picture %>
    <%= f.input :start_date, order: [:day, :month, :year] %>
    <%= f.input :end_date, order: [:day, :month, :year] %>
    <%= f.input :link %>
    <%= f.association :tag %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sals/index.html.erb
<%= link_to "Past SALs", archive_sals_path, class: "btn btn-success padding btn-lg" %>
<%=  mail_to "sarah@stitchingly.com", "Suggest a New SAL", subject: "Suggest a New SAL", class: "btn btn-default padding btn-lg" %>
<div class="row bootstrap snippets" id="real-estates-columns">
  <%= render @sals %>
</div>



app/views/sals/new.html.erb
<h1>Add a New Sal</h1>

<%= simple_form_for(@sal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :company %>
    <%= f.input :picture %>
    <%= f.input :start_date, order: [:day, :month, :year] %>
    <%= f.input :end_date, order: [:day, :month, :year] %>
    <%= f.input :link %>
    <%= f.association :tag %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sals/show.html.erb
<div class="booyah-box col-xs-12">
  <div class="panel">
    <div class="panel-body">
      <h1 class="text-center">
        <%= @sal.name %> 
        <% if @sal.link? %>
        <%= link_to "Buy", "http://#{@sal.link}", class: "btn btn-success pull-right", target: :_blank %>
        <% end %>
      </h1>
      <div class="col-md-6 col-sm-12 col-xs-12">
        <% if @sal.picture? %>
            <%= image_tag(@sal.picture, class: "img-thumbnail img-responsive") %>
        <% else %>
            <%= image_tag("noimage.jpeg", class: "img-thumbnail img-responsive") %>
        <% end %>
      </div>
      <div class="col-md-6 col-sm-12 col-xs-12">
      <% if @sal.link? %>
        <h3 class="text-center">By <%= link_to @sal.company, "http://#{@sal.company_link}"  %></h3>
      <% else %>
        <h3 class="text-center">By <%= @sal.company %></h3>
      <% end %>
        <hr>
        <% if @sal.start_date %>
          <h4 class="text-center"><%= @sal.start_date.strftime("%b %d, %Y") %>
        <% else %>
          <h4 class="text-center">Not Started
        <% end %>
        <% if @sal.end_date && @sal.start_date %>
          - <%= @sal.end_date.strftime("%b %d, %Y") %></h4>
        <% elsif @sal.start_date %>
          - Not Finished</h4>
        <% end %>
        </br>
        <% if @sal.notes? %>
          <%= @sal.notes.html_safe %>
        <% end %>
      </div>
    </div>
  </div>
</div> 
<%= render 'releases' %>
<%= render 'projects' %>