config/routes.rb
Rails.application.routes.draw do

  
  resources :designers
  root 'pages#home'

  resources :sals do 
    collection do
      get 'archive'
    end
    resources :releases
  end

  resources :tags

  resources :features do
    collection do
      get 'completed'
    end
    member do
      put "like", to: "features#upvote"
      put "dislike", to: "features#downvote"
    end
  end

  get '/about', to: 'pages#about', as: 'about'
  devise_for :users 
  resources :user_flosses
  resources :flosses do
    member do
      put "increase", to: "flosses#increase"
      put "decrease", to: "flosses#decrease"
    end
  end
  resources :fabrics
  get '/projects', to: 'projects#all', as: 'projects'
  get '/projects/dashboard', to: 'projects#dashboard', as: 'dashboard'
  get '/projects/dashboard/archive', to: 'projects#archive', as: 'archive'
  get '/projects/dashboard/wishlist', to: 'projects#wishlist', as: 'wishlist'
  get '/projects/dashboard/all', to: 'projects#dashboardall', as: 'dashboardall'
  resources :users, only: [:index, :show, :all] do
    resources :projects do
      member do
        put "like", to: "projects#like"
        put "dislike", to: "projects#dislike"
      end
      resources :updates
    end
  end

  get "/flosses/increase_with_jquery/:id", to: "flosses#increase_with_jquery"
  get "/flosses/decrease_with_jquery/:id", to: "flosses#decrease_with_jquery"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :updates, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  mount_uploader :picture, PictureUploader
  validates :name, presence: true
  validates :status, presence: true
  validates :name, :uniqueness => {:scope=>:user_id}
  validates :user, presence: true
  acts_as_votable
  scope :notprivate, -> { where(private: false) }
  scope :nopicture, -> { where.not(:picture => nil) }
  scope :started, -> { where.not(:start_date => nil) }
  scope :notfinished, -> { where(:finish_date => nil) }

  def email_format
    self.user.email.split("@").first
  end

  def total_hours
    self.updates.sum(:hours)
  end

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_user, except: [:new, :all, :dashboard, :archive, :wishlist, :dashboardall]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /projects
  # GET /projects.json
  def index
    @user = User.friendly.find(params[:user_id])
    if @user == current_user
      @q = @user.projects.order(updated_at: :desc).ransack(params[:q])
    else
      @q = @user.projects.notprivate.order(updated_at: :desc).ransack(params[:q])
    end
    @projects = @q.result
  end

  def dashboard
    @user = current_user
    @projects = @user.projects.started.notfinished
  end

  def dashboardall
    @user = current_user
    @projects = @user.projects
  end

  def archive
    @user = current_user
    @projects = @user.projects.where.not(:finish_date => nil)
  end

  def wishlist
    @user = current_user
    @projects = @user.projects.where(:start_date => nil)
  end

  def all
    @q = Project.notprivate.nopicture.order(updated_at: :desc).ransack(params[:q])
    @projects = @q.result
    @projects = @q.result.paginate(:page => params[:page], :per_page => 30)
  end

  def alls
    @q = Project.notprivate.ransack(params[:q])
    @projects = @q.result
    @projects = @q.result.paginate(:page => params[:page], :per_page => 30)
  end

  def like
    @project = Project.find(params[:id])
    @project.liked_by current_user
    redirect_to projects_path
  end

  def dislike
    @project = Project.find(params[:id])
    @project.disliked_by current_user
    redirect_to projects_path
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = @user.projects.find(params[:id])
    @updates = @project.updates.order(update_date: :desc)
    @updates = @updates.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    @project = @user.projects.find(params[:id])
  end

  # POST /projects
  # POST /projects.json

  def create
    @project = @user.projects.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to user_project_path(@user, @project), notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @user_floss }
      else
        format.html { render :new }
        format.json { render json: @user_floss.errors, status: :unprocessable_entity }
      end
    end
  end
 

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    @project = @user.projects.find(params[:id])
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to user_project_path(@user, @project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = @user.projects.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to user_projects_path(@user), notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_user
      @user = User.friendly.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :notes, :progress, :status, :user_id, :pattern_name, :pattern_designer, :fabric_brand, :fabric_colour, :fabric_count, :thread_brand, :picture, :start_date, :finish_date, :private, :tag_list)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for @project, url: user_projects_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: 'Name of your project' %>
    <%= f.input :picture %>
    <%= f.input :status, collection: ['Wishlist', 'Kitted','WIP', 'UFO', 'FFO', 'Finish'], prompt: "Select a Status" %>
    <%= f.input :progress, placeholder: '% Complete' %>
    <%= f.input :pattern_name %>
    <%= f.input :pattern_designer %>
    <%= f.input :fabric_brand %>
    <%= f.input :fabric_colour %>
    <%= f.input :fabric_count %>
    <%= f.input :thread_brand %>
    <%= f.input :notes, placeholder: 'Any notes about your project or changes you have made.' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success padding" %>
    <%= link_to 'Back', :back, class: "btn btn-default padding pull-right" %>
  </div>
<% end %>

app/views/projects/_projectdisplay.html.erb
<div class="row bootstrap snippets" id="real-estates-columns">
  <% @projects.each do |project| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
            <%= link_to image_tag(project.picture, class: "img-responsive"), user_project_path(project.user, project) %>
            <div class="title-realestates-columns">
              <h4><%= link_to project.name, user_project_path(project.user, project) %><%= link_to project.status, "#", class: "btn btn-primary pull-right" %></h4>
              <% if project.start_date %>
                  <%= project.start_date.strftime("%b %d, %Y") %> -
                  <% else %>
                    Not Started
                  <% end %>
                  <% if project.finish_date %>
                    <%= project.finish_date.strftime("%b %d, %Y") %> 
                  <% end %>
              <hr>
            </div>

              <% if project.user.username && !project.user.username.empty? %>
                <%= link_to project.user.username, user_projects_path(project.user), class: "btn btn-primary" %>
              <% else %>
                <%= link_to project.email_format, user_projects_path(project.user), class: "btn btn-primary" %> 
              <% end %>
              <%= link_to '<i class="fa fa-heart" aria-hidden="true"> Favourite</i>'.html_safe, "#", class: "btn btn-danger pull-right" %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/projects/_searchform.html.erb
<div class="row">
<%= search_form_for @q, url: user_projects_path, :builder => SimpleForm::FormBuilder do |f| %>
  <div class="col-md-3">
    <%= f.input :name_or_pattern_name_cont, label: 'Project Name or Pattern Name' %>
  </div>
  <div class="col-md-3">
    <%= f.input :fabric_colour_or_fabric_brand_cont, label: 'Fabric  Brand or Colour' %>
  </div>
  <div class="col-md-3">
    <%= f.input :status_cont, label: 'Project Status' %>
  </div>
  <div class="col-md-3">
    <%= f.input :thread_brand_cont, label: 'Thread Brand' %>
  </div>
</div>
<div class="row test-center">
  <%= f.button :submit, "Search", class: "btn btn-primary padding" %>
</div>
<% end %>

app/views/projects/_updates.html.erb
<div class="row bootstrap snippets" id="real-estates-columns">
  <% @updates.each do |update| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
          <%= image_tag(update.picture, class: "img-responsive") %>
          <% if update.hours %>
          <h4 class="text-center"><%= update.hours %> hours on <%= update.update_date.strftime("%b %d, %Y") %></h4>
          <% else %>
          <h4 class="text-center"><%= update.update_date.strftime("%b %d, %Y") %></h4>
          <% end %>
          <hr>
          <% if @project.user == current_user %>
            <%= link_to "Edit", edit_user_project_update_path(@user, @project, update), class: "btn btn-primary" %>
            <%= link_to "Delete", user_project_update_path(@user, @project, update), :confirm => "Are you sure?", :method => :delete, class: "btn btn-danger" %> 
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="text-center">
  <%= will_paginate @updates, renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/all.html.erb
<div class="booyah-box">
  <div class="row">
  <%= search_form_for @q, url: projects_path, :builder => SimpleForm::FormBuilder do |f| %>
    <div class="col-md-3">
      <%= f.input :name_or_pattern_name_cont, label: 'Project Name or Pattern Name' %>
    </div>
    <div class="col-md-3">
      <%= f.input :pattern_designer_cont, label: 'Pattern Designer' %>
    </div>
    <div class="col-md-3">
      <%= f.input :fabric_colour_or_fabric_brand_cont, label: 'Fabric  Brand or Colour' %>
    </div>
    <div class="col-md-3">
      <%= f.input :status_cont, label: 'Project Status' %>
    </div>
  </div>
  <div class="row test-center">
    <%= f.button :submit, "Search", class: "btn btn-success padding" %>
  </div>
  <% end %>
</div>
<div class="row bootstrap snippets" id="real-estates-columns">
  <% @projects.each do |project| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
        <% if project.picture? %>
            <%= link_to image_tag(project.picture, class: "img-responsive"), user_project_path(project.user, project) %>
        <% else %>
            <%= link_to image_tag("noimage.jpeg", class: "img-responsive"), user_project_path(project.user, project) %>
        <% end %>
            <div class="title-realestates-columns">
              <h4><%= link_to project.name, user_project_path(project.user, project) %><%= link_to project.status, "#", class: "btn btn-primary pull-right" %></h4>
              <hr>
            </div>
            <%= link_to project.user.username, user_path(project.user), class: "btn btn-primary" %>         
            <% if current_user.liked? project %>
              <%= link_to  dislike_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                  <i class="fa fa-heart" aria-hidden="true">
                    <% if project.get_likes.size > 0 %>
                      <%= project.get_likes.size %>
                    <% else %>
                    Like
                    <% end %>
                  </i>
                <% end %>
            <% else %>
              <%= link_to  like_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                  <i class="fa fa-heart-o" aria-hidden="true">
                    <% if project.get_likes.size > 0 %>
                      <%= project.get_likes.size %>
                    <% else %>
                    Like
                    <% end %>
                  </i>
                <% end %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<div class="text-center">
  <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/dashboard.html.erb
      <div class="row">
        <div class="col-lg-12">
          <%= link_to "New Project", new_user_project_path(current_user), class: "btn btn-success padding" %>
          <%= link_to "Wish List", wishlist_path, class: "btn btn-default padding pull-right" %>
          <%= link_to "All Projects", dashboardall_path, class: "btn btn-default padding pull-right" %>
          <%= link_to "Archive", archive_path, class: "btn btn-default padding pull-right" %>
          <div class="content-box project-wrapper">
          <% @projects.each do |project | %>
            <div class="project-item">
              <div class="status-desktop pull-left">
                <span class="active"><%= project.status %></span>
              </div>
              <div class="project-box white-bg pull-left">
                <div class="status-mobile pull-left">
                  <span class="active"><%= project.status %></span>
                </div>
                <div class="project-tools mobile-tools text-right pull-left">
                  <a href="#"><i class="fa fa-eye"></i></a>
                  <a href="#"><i class="fa fa-pencil"></i></a>
                  <a href="#"><i class="fa fa-close"></i></a>
                </div>
                <div class="pull-left">
                  <div class="resp-avatars">
                    <div class="name"><strong><%= project.name %></strong></div>
                    <% if project.picture? %>
                      <%= image_tag(project.picture, class: "img-rounded") %>
                    <% else %>
                        <%= image_tag("noimage.jpeg", class: "img-rounded") %>
                    <% end %>
                  </div>
                </div>

                <div class="project-name pull-left">
                  <div class="created"><strong>
                  <% if project.start_date %>
                  <%= project.start_date.strftime("%b %d, %Y") %> -
                  <% else %>
                    Not Started
                  <% end %>
                  <% if project.finish_date %>
                    <%= project.finish_date.strftime("%b %d, %Y") %> 
                  <% end %>
                    </strong></span></div>
                  <div class="created">Last Updated <%= project.updated_at.strftime("%b %d, %Y") %></span></div>
                </div>
                <div class="project-progress pull-left">
                  <span class="task-title"><span><%= project.progress %>% Complete</span></span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" aria-valuenow="<%= project.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.progress %>%;">
                    </div>
                  </div>
                </div>
                <div class="project-tools desktop-tools text-right pull-left">
                  <%= link_to(user_project_path(project.user, project)) do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to(edit_user_project_path(project.user, project)) do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to(user_project_path(project.user, project), method: :delete, data: { confirm: "Are you sure?" }) do %> 
                    <i class="fa fa-close"></i>
                  <% end %>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>

app/views/projects/dashboardall.html.erb
<h1>All Projects 
  <%= link_to "Archive", archive_path, class: "btn btn-default padding pull-right" %>
  <%= link_to "Wishlist", wishlist_path, class: "btn btn-default padding pull-right" %>
  <%= link_to "Project Dashboard", dashboard_path, class: "btn btn-success padding pull-right" %>
  </h1>
    <div class="row">
        <div class="col-lg-12"> 
          <div class="content-box project-wrapper">
          <% @projects.each do |project | %>
            <div class="project-item">
              <div class="status-desktop pull-left">
                <span class="active"><%= project.status %></span>
              </div>
              <div class="project-box white-bg pull-left">
                <div class="status-mobile pull-left">
                  <span class="active"><%= project.status %></span>
                </div>
                <div class="project-tools mobile-tools text-right pull-left">
                  <a href="#"><i class="fa fa-eye"></i></a>
                  <a href="#"><i class="fa fa-pencil"></i></a>
                  <a href="#"><i class="fa fa-close"></i></a>
                </div>
                <div class="pull-left">
                  <div class="resp-avatars">
                    <div class="name"><strong><%= project.name %></strong></div>
                    <% if project.picture? %>
                      <%= image_tag(project.picture, class: "img-rounded") %>
                    <% else %>
                        <%= image_tag("noimage.jpeg", class: "img-rounded") %>
                    <% end %>
                  </div>
                </div>

                <div class="project-name pull-left">
                  <div class="created"><strong>
                  <% if project.start_date %>
                  <%= project.start_date.strftime("%b %d, %Y") %> -
                  <% else %>
                    Not Started
                  <% end %>
                  <% if project.finish_date %>
                    <%= project.finish_date.strftime("%b %d, %Y") %> 
                  <% end %>
                    </strong></span></div>
                  <div class="created">Last Updated <%= project.updated_at.strftime("%b %d, %Y") %></span></div>
                </div>
                <div class="project-progress pull-left">
                  <span class="task-title"><span><%= project.progress %>% Complete</span></span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" aria-valuenow="<%= project.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.progress %>%;">
                    </div>
                  </div>
                </div>
                <div class="project-tools desktop-tools text-right pull-left">
                  <%= link_to(user_project_path(project.user, project)) do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to(edit_user_project_path(project.user, project)) do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to(user_project_path(project.user, project), method: :delete, data: { confirm: "Are you sure?" }) do %> 
                    <i class="fa fa-close"></i>
                  <% end %>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>

app/views/projects/index.html.erb
<div class="panel">
<div class="row">
<% if user_signed_in? && @user == current_user %>
  <%= link_to "New Project", new_user_project_path(current_user), class: "btn btn-success padding" %>
<% end %>
</div>
<%= render 'searchform' %>
<table class="table table-bordered table-striped"> 
  <thead> 
    <tr> 
      <th><%= sort_link(@q, :name, 'Project Name', default_order: :desc) %></th> 
      <th><%= sort_link(@q, :created_at, 'Date Created', default_order: :desc) %></th> 
      <th><%= sort_link(@q, :status, 'Project Status', default_order: :desc) %></th> 
      <th><%= sort_link(@q, :progress, 'Project Progress', default_order: :desc) %></th> 
    </tr> 
  </thead> 
</table>
</div>
<div class="row bootstrap snippets" id="real-estates-columns">
  <% @projects.each do |project| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <div class="panel">
        <div class="panel-body">
          <% if project.picture? %>
            <%= link_to image_tag(project.picture, class: "img-responsive"), user_project_path(project.user, project) %>
          <% else %>
            <%= link_to image_tag("noimage.jpeg", class: "img-responsive"), user_project_path(project.user, project) %>
          <% end %>
          <div class="title-realestates-columns">
            <h4><%= link_to project.name, user_project_path(project.user, project) %><%= link_to project.status, "#", class: "btn btn-primary pull-right" %></h4>
            <% if project.start_date %>
              <%= project.start_date.strftime("%b %d, %Y") %> -
            <% else %>
              Not Started
            <% end %>
            <% if project.finish_date %>
              <%= project.finish_date.strftime("%b %d, %Y") %> 
            <% end %>
            <hr>
          </div>
          <% if project.user == current_user && project.private == true %>
            <%= link_to "Private", user_project_path(project.user, project), class: "btn btn-danger" %>
            <%= link_to  '#', class: "btn btn-danger pull-right" do %>
              <i class="fa fa-heart" aria-hidden="true">
                <%= project.get_likes.size %>
              </i>
            <% end %>
            <% elsif project.user == current_user %>
              <%= link_to "View", user_project_path(project.user, project), class: "btn btn-primary" %>
              <%= link_to  '#', class: "btn btn-danger pull-right" do %>
                <i class="fa fa-heart" aria-hidden="true">
                  <%= project.get_likes.size %>
                </i>
            <% end %>
            <% else %>
              <%= link_to project.user.username, user_projects_path(project.user), class: "btn btn-primary" %>
              <% if user_signed_in? %>
                <% if current_user.liked? project %>
                  <%= link_to  dislike_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                  <i class="fa fa-heart" aria-hidden="true">
                    <% if project.get_likes.size > 0 %>
                      <%= project.get_likes.size %>
                    <% else %>
                      Like
                    <% end %>
                  </i>
                <% end %>
                <% else %>
                  <%= link_to  like_user_project_path(project.user, project), method: :put, class: "btn btn-danger pull-right" do %>
                    <i class="fa fa-heart-o" aria-hidden="true">
                      <% if project.get_likes.size > 0 %>
                        <%= project.get_likes.size %>
                      <% else %>
                        Like
                      <% end %>
                    </i>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <%= link_to "Back", :back, class: "btn btn-default" %>
  <% if @project.private == false || @project.user == current_user %>
    <h1 class="text-center"><%= @project.name %><%= link_to @project.status, "#", class: "btn btn-primary pull-right" %>
      <% if @project.private == true %>
        <%= link_to "Private", "#", class: "btn btn-danger pull-right" %>
      <% end %>
    </h1>
  <div class="row">
    <div class="col-md-4">
      <% if @project.picture? %>
        <%= image_tag(@project.picture, class: "img-thumbnail") %>
      <% else %>
        <%= image_tag("noimage.jpeg", class: "img-thumbnail") %>
      <% end %>
      </br>
      </br>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Tags</h3>
        </div>
        <div class="panel-body">
          <p>
            <% @project.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag) %>
            <% end %>
          </p>
        </div>
      </div>
      <% if @project.user == current_user %>
        <%= link_to "Edit", edit_user_project_path(@project.user, @project), class: "btn btn-primary" %>
        <%= link_to "Delete", [@project.user, @project], :confirm => "Are you sure?", :method => :delete, class: "btn btn-danger" %> 
        <%= link_to "New Update", new_user_project_update_path(@project.user, @project), class: "btn btn-success" %> 
      <% end %>
    </div>
    <div class="col-md-6">
    <% if @project.progress %>
      <div class="progress">
        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= @project.progress %>%;">
          <%= @project.progress %>%
        </div>
      </div>
      <% end %>
      <table class="table">
        <tr>
          <td>Start Date:</td>
            <% if @project.start_date %>
          <td><%= @project.start_date.strftime("%b %d, %Y") %></td>
          <% else %>
            <td>Not Started</td>
          <% end %>
        </tr>  
        <tr>
          <td>Finish Date:</td>
          <% if @project.finish_date %>
            <td><%= @project.finish_date.strftime("%b %d, %Y") %></td>
          <% else %>
            <td>Not Finished</td>
          <% end %>
        </tr>  
        <tr>
          <td>Total Hours:</td>
          <td><%= @project.total_hours %></td>
        </tr> 
        <tr>
          <td>Pattern Name:</td>
          <td><%= @project.pattern_name %></td>
        </tr>  
        <tr>
          <td>Pattern Designer:</td>
          <td><%= @project.pattern_designer %></td>
        </tr> 
        <tr>
          <td>Fabric Brand:</td>
          <td><%= @project.fabric_brand %></td>
        </tr> 
        <tr>
          <td>Fabric Colour:</td>
          <td><%= @project.fabric_colour %></td>
        </tr>  
        <tr>
          <td>Fabric Count:</td>
          <td><%= @project.fabric_count %></td>
        </tr>  
        <tr>
          <td>Thread Brand:</td>
          <td><%= @project.thread_brand %></td>
        </tr>  
      </table>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Notes</h3>
        </div>
        <div class="panel-body">
          <%= @project.notes %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'updates' %>
<% else %>
  <h1 class="text-center">This project is private </h1>
<% end %>

app/views/projects/wishlist.html.erb
<h1>Wishlist 
  <%= link_to "Archive", archive_path, class: "btn btn-default padding pull-right" %>
  <%= link_to "All Projects", dashboardall_path, class: "btn btn-default padding pull-right" %>
  <%= link_to "Project Dashboard", dashboard_path, class: "btn btn-success padding pull-right" %>
</h1>
    <div class="row">
        <div class="col-lg-12"> 
          <div class="content-box project-wrapper">
          <% @projects.each do |project | %>
            <div class="project-item">
              <div class="status-desktop pull-left">
                <span class="active"><%= project.status %></span>
              </div>
              <div class="project-box white-bg pull-left">
                <div class="status-mobile pull-left">
                  <span class="active"><%= project.status %></span>
                </div>
                <div class="project-tools mobile-tools text-right pull-left">
                  <a href="#"><i class="fa fa-eye"></i></a>
                  <a href="#"><i class="fa fa-pencil"></i></a>
                  <a href="#"><i class="fa fa-close"></i></a>
                </div>
                <div class="pull-left">
                  <div class="resp-avatars">
                    <div class="name"><strong><%= project.name %></strong></div>
                    <% if project.picture? %>
                      <%= image_tag(project.picture, class: "img-rounded") %>
                    <% else %>
                        <%= image_tag("noimage.jpeg", class: "img-rounded") %>
                    <% end %>
                  </div>
                </div>

                <div class="project-name pull-left">
                  <div class="created"><strong>
                  <% if project.start_date %>
                  <%= project.start_date.strftime("%b %d, %Y") %> -
                  <% else %>
                    Not Started
                  <% end %>
                  <% if project.finish_date %>
                    <%= project.finish_date.strftime("%b %d, %Y") %> 
                  <% end %>
                    </strong></span></div>
                  <div class="created">Last Updated <%= project.updated_at.strftime("%b %d, %Y") %></span></div>
                </div>
                <div class="project-progress pull-left">
                  <span class="task-title"><span><%= project.progress %>% Complete</span></span>
                  <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-success" role="progressbar" aria-valuenow="<%= project.progress %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= project.progress %>%;">
                    </div>
                  </div>
                </div>
                <div class="project-tools desktop-tools text-right pull-left">
                  <%= link_to(user_project_path(project.user, project)) do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to(edit_user_project_path(project.user, project)) do %>
                    <i class="fa fa-pencil"></i>
                  <% end %>
                  <%= link_to(user_project_path(project.user, project), method: :delete, data: { confirm: "Are you sure?" }) do %> 
                    <i class="fa fa-close"></i>
                  <% end %>
                </div>
                <div class="clearfix"></div>
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>