config/routes.rb
Rails.application.routes.draw do

  
  resources :designers
  root 'pages#home'

  resources :sals do 
    collection do
      get 'archive'
    end
    resources :releases
  end

  resources :tags

  resources :features do
    collection do
      get 'completed'
    end
    member do
      put "like", to: "features#upvote"
      put "dislike", to: "features#downvote"
    end
  end

  get '/about', to: 'pages#about', as: 'about'
  devise_for :users 
  resources :user_flosses
  resources :flosses do
    member do
      put "increase", to: "flosses#increase"
      put "decrease", to: "flosses#decrease"
    end
  end
  resources :fabrics
  get '/projects', to: 'projects#all', as: 'projects'
  get '/projects/dashboard', to: 'projects#dashboard', as: 'dashboard'
  get '/projects/dashboard/archive', to: 'projects#archive', as: 'archive'
  get '/projects/dashboard/wishlist', to: 'projects#wishlist', as: 'wishlist'
  get '/projects/dashboard/all', to: 'projects#dashboardall', as: 'dashboardall'
  resources :users, only: [:index, :show, :all] do
    resources :projects do
      member do
        put "like", to: "projects#like"
        put "dislike", to: "projects#dislike"
      end
      resources :updates
    end
  end

  get "/flosses/increase_with_jquery/:id", to: "flosses#increase_with_jquery"
  get "/flosses/decrease_with_jquery/:id", to: "flosses#decrease_with_jquery"
end

app/controllers/user_flosses_controller.rb
class UserFlossesController < ApplicationController
  before_action :set_user_floss, only: [:show, :edit, :update, :destroy]

  # GET /user_flosses
  # GET /user_flosses.json
  def index
    @user_flosses = UserFloss.all
  end

  # GET /user_flosses/1
  # GET /user_flosses/1.json
  def show
  end

  # GET /user_flosses/new
  def new
    @user_floss = UserFloss.new
  end

  # GET /user_flosses/1/edit
  def edit
  end

  # POST /user_flosses
  # POST /user_flosses.json
  def create
    @user_floss = UserFloss.new(user_floss_params)
    respond_to do |format|
      if @user_floss.save
        format.html { redirect_to :back, notice: 'User floss was successfully created.' }
        format.json { render :show, status: :created, location: @user_floss }
      else
        format.html { render :new }
        format.json { render json: @user_floss.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_flosses/1
  # PATCH/PUT /user_flosses/1.json
  def update
    respond_to do |format|
      if @user_floss.update(user_floss_params)
        format.html { redirect_to :back, notice: 'Quantity was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_floss }
        format.js   { render :layout => false }
      else
        format.html { redirect_to :back, alert: 'Quantity was not successfully updated.' }
        format.json { render json: @user_floss.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /user_flosses/1
  # DELETE /user_flosses/1.json
  def destroy
    @user_floss.destroy
    respond_to do |format|
      format.html { redirect_to flosses_path, notice: 'User floss was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_floss
      @user_floss = UserFloss.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_floss_params
      params.require(:user_floss).permit(:user_id, :floss_id, :floss_quantity)
    end
end

app/helpers/user_flosses_helper.rb
module UserFlossesHelper
end

app/views/user_flosses/_form.html.erb
<%= simple_form_for(@user_floss) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :floss %>
    <%= f.input :floss_quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/user_flosses/edit.html.erb
<h1>Editing User Floss</h1>

<%= render 'form', user_floss: @user_floss %>

<%= link_to 'Show', @user_floss %> |
<%= link_to 'Back', user_flosses_path %>

app/views/user_flosses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Flosses</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Floss</th>
      <th>Floss quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_flosses.each do |user_floss| %>
      <tr>
        <td><%= user_floss.user %></td>
        <td><%= user_floss.floss %></td>
        <td><%= user_floss.floss_quantity %></td>
        <td><%= link_to 'Show', user_floss %></td>
        <td><%= link_to 'Edit', edit_user_floss_path(user_floss) %></td>
        <td><%= link_to 'Destroy', user_floss, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Floss', new_user_floss_path %>

app/views/user_flosses/new.html.erb
<h1>New User Floss</h1>

<%= render 'form', user_floss: @user_floss %>

<%= link_to 'Back', user_flosses_path %>

app/views/user_flosses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_floss.user %>
</p>

<p>
  <strong>Floss:</strong>
  <%= @user_floss.floss %>
</p>

<p>
  <strong>Floss quantity:</strong>
  <%= @user_floss.floss_quantity %>
</p>

<%= link_to 'Edit', edit_user_floss_path(@user_floss) %> |
<%= link_to 'Back', user_flosses_path %>

app/views/user_flosses/update.js.erb
$('#floss').html("<%= escape_javascript(render(:partial => 'flosses/floss')).html_safe %>");