config/routes.rb
Rails.application.routes.draw do

  
  resources :designers
  root 'pages#home'

  resources :sals do 
    collection do
      get 'archive'
    end
    resources :releases
  end

  resources :tags

  resources :features do
    collection do
      get 'completed'
    end
    member do
      put "like", to: "features#upvote"
      put "dislike", to: "features#downvote"
    end
  end

  get '/about', to: 'pages#about', as: 'about'
  devise_for :users 
  resources :user_flosses
  resources :flosses do
    member do
      put "increase", to: "flosses#increase"
      put "decrease", to: "flosses#decrease"
    end
  end
  resources :fabrics
  get '/projects', to: 'projects#all', as: 'projects'
  get '/projects/dashboard', to: 'projects#dashboard', as: 'dashboard'
  get '/projects/dashboard/archive', to: 'projects#archive', as: 'archive'
  get '/projects/dashboard/wishlist', to: 'projects#wishlist', as: 'wishlist'
  get '/projects/dashboard/all', to: 'projects#dashboardall', as: 'dashboardall'
  resources :users, only: [:index, :show, :all] do
    resources :projects do
      member do
        put "like", to: "projects#like"
        put "dislike", to: "projects#dislike"
      end
      resources :updates
    end
  end

  get "/flosses/increase_with_jquery/:id", to: "flosses#increase_with_jquery"
  get "/flosses/decrease_with_jquery/:id", to: "flosses#decrease_with_jquery"
end

app/models/update.rb
class Update < ApplicationRecord
  belongs_to :project
  mount_uploader :picture, PictureUploader
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_project
  before_action :authenticate_user!, except: [:index, :show]


  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.all
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
    @update = @project.updates.find(params[:id])
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
    @update = @project.updates.find(params[:id])
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = @project.updates.new(update_params)
    respond_to do |format|
      if @update.save
        format.html { redirect_to user_project_path(current_user, @project), notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    @update = @project.updates.find(params[:id])
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to user_project_path(current_user, @project), notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update = @project.updates.find(params[:id])
    @update.destroy
    respond_to do |format|
      format.html { redirect_to user_project_path(current_user, @project), notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:picture, :update_date, :hours)
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/updates/_form.html.erb
<%= simple_form_for(@update), url: user_project_updates_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :picture %>
    <%= f.input :string %>
    <%= f.input :update_date %>
    <%= f.input :date %>
    <%= f.input :hours %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= simple_form_for @update, url: user_project_update_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :picture %>
    <%= f.input :update_date %>
    <%= f.input :hours %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update", class: "btn btn-success" %>
  </div>
<% end %>

<%= link_to 'Back',  user_project_path(current_user, @update.project) %>
 

app/views/updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Updates</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Update date</th>
      <th>Hours</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= image_tag update.picture %></td>
        <td><%= update.update_date %></td>
        <td><%= update.hours %></td>
        <td><%= link_to 'Show', user_project_update_path(@project.user, @project, update) %></td>
        <td><%#= link_to 'Edit', edit_user_project_update_path(update.project, update) %></td>
        <td><%#= link_to 'Destroy', user_project_update_path(update.project, update), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Update',  new_user_project_update_path %>

app/views/updates/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
<h1>New Update</h1>

<%= simple_form_for @update, url: user_project_updates_path do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :picture %>
    <%= f.input :update_date %>
    <%= f.input :hours %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back',  user_project_updates_path %>
</div>

app/views/updates/show.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @update.picture %>
</p>


<p>
  <strong>Update date:</strong>
  <%= @update.update_date %>
</p>


<p>
  <strong>Hours:</strong>
  <%= @update.hours %>
</p>

<%= link_to 'Edit', edit_update_path(@update) %> |
<%= link_to 'Back', updates_path %>
</div>